version: '3.9'

services:
  transcrib-app:
    build: .
    container_name: transcrib-app
    ports:
      - "5003:5003"
    restart: unless-stopped
    # Для GPU-поддержки раскомментируйте следующие строки:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # runtime: nvidia
